# LA Crime: Database models

#### Load Python tools and Jupyter config

In [2]:
import os
import json
import requests
import pandas as pd
import jupyter_black
from sodapy import Socrata

In [3]:
jupyter_black.load()
pd.options.display.max_columns = 100
pd.options.display.max_rows = 1000
pd.options.display.max_colwidth = None

In [4]:
today = pd.Timestamp("today").strftime("%Y%m%d")
today_epoch = int(pd.Timestamp.today().timestamp())

---

## Read

In [13]:
df = pd.read_parquet("../data/processed/incidents_df.parquet")
df[["premis_cd_id", "weapon_used_cd_id"]].isna().value_counts()

premis_cd_id  weapon_used_cd_id
False         True                 1940479
              False                 999336
True          True                     494
              False                    248
Name: count, dtype: int64

In [14]:
df.head()

,dr_no,date_rptd,date_occ,time_occ,area_name,rpt_dist_no,part_1_2,crm_cd_desc,mocodes,vict_age,vict_descent,premis_desc,weapon_desc,status_desc,crm_cd_1,crm_cd_2,crm_cd_3,crm_cd_4,location,cross_street,lat,lon,datetime_occurred,area_id,crm_cd_id,premis_cd_id,weapon_used_cd_id,status_id,vict_sex_id
0,001307355,None,None,13:50:00,Newton,1385,2,VIOLATION OF COURT ORDER,0913 1814 2000,48,H,SINGLE FAMILY DWELLING,nan,Adult Arrest,900,nan,nan,nan,300 E GAGE AV,nan,33.9825,-118.2695,None,1,1,1.0,NaN,1,1
1,011401303,None,None,00:45:00,Pacific,1485,2,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)",0329,0,W,STREET,nan,Invest Cont,740,nan,nan,nan,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962,None,2,2,2.0,NaN,2,1
2,070309629,None,None,15:15:00,Newton,1324,2,OTHER MISCELLANEOUS CRIME,0344,0,H,ALLEY,nan,Invest Cont,946,nan,nan,nan,1300 E 21ST ST,nan,34.0224,-118.2524,None,1,3,3.0,NaN,2,1
3,090631215,None,None,01:50:00,Hollywood,0646,2,VIOLATION OF COURT ORDER,1100 0400 1402,47,W,STREET,HAND GUN,Invest Cont,900,998,nan,nan,CAHUENGA BL,HOLLYWOOD BL,34.1016,-118.3295,None,3,1,2.0,1.0,2,2
4,100100501,None,None,21:00:00,Central,0176,1,"RAPE, ATTEMPTED",0400,47,H,ALLEY,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Invest Cont,122,nan,nan,nan,8TH ST,SAN PEDRO ST,34.0387,-118.2488,None,4,4,3.0,2.0,2,2